# Generated by Django 5.0.6 on 2024-06-12 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blogcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
